name: owl_hris
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-143.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ## Shimmer
  shimmer: ^2.0.0

  ## Image picker
  image_picker: ^0.8.7

  ## Portal
  flutter_portal: ^1.1.3

  ## Geolocator
  geolocator: ^10.0.1

  ## Local Auth
  local_auth: ^2.1.7

  ## Timeline Tile
  timeline_tile: ^2.0.0

  ## Bitmap
  # bitmap: ^0.1.3

  ## Camera
  camera: ^0.10.5+2

  ## Styled Text
  styled_text: ^7.0.0

  ## SVG
  flutter_svg: ^2.0.2

  ## State Management
  flutter_bloc: ^8.1.2

  ## Comparing Dart Object
  equatable: ^2.0.5

  ## Service Locator
  get_it: ^7.6.0

  ## Hero Icons
  heroicons: ^0.8.0

  ## DateFormat
  intl: ^0.18.1

  ## Database
  floor: ^1.4.2

  ## Lottie
  lottie: ^2.5.0

  ## Request Api
  retrofit: ^4.0.1

  ## Functional Programming
  dartz: ^0.10.1

  ## Hooks
  flutter_hooks: ^0.18.3

  ## Cached Image
  cached_network_image: ^3.2.0

  ## Json
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  ## Screen Util
  flutter_screenutil: ^5.8.4

  ## Navigation Router
  # go_router: ^10.0.0
  auto_route: ^7.7.1

  ## Local Store Data
  shared_preferences: ^2.2.0

  ## Mock Testing
  mockito: ^5.4.2

  ## Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  auto_route_generator: ^7.2.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.6
  test: ^1.24.2

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/font/
    - assets/image/
    - assets/image/devs/
    - assets/icons/
    - assets/lotties/

fonts:
  - family: Inter
    fonts:
      - asset: assets/font/Inter-Regular.ttf
        weight: 400
      - asset: assets/font/Inter-Medium.ttf
        weight: 500
      - asset: assets/font/Inter-Light.ttf
        weight: 300
      - asset: assets/font/Inter-ExtraLight.ttf
        weight: 200
      - asset: assets/font/Inter-ExtraBold.ttf
        weight: 800
      - asset: assets/font/Inter-SemiBold.ttf
        weight: 600
      - asset: assets/font/Inter-Thin.ttf
        weight: 100
      - asset: assets/font/Inter-Bold.ttf
        weight: 700
      - asset: assets/font/Inter-Black.ttf
        weight: 900
