// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaxe2rd3AV6WrZTbOWqr42v7HTcTpoprQ',
    appId: '1:541373305176:web:e05069262c87c77f64952d',
    messagingSenderId: '541373305176',
    projectId: 'owl-ess-fc85e',
    authDomain: 'owl-ess-fc85e.firebaseapp.com',
    storageBucket: 'owl-ess-fc85e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdMteY3RV65-jZqUzQGIUCNSvvYmj40Y0',
    appId: '1:541373305176:android:1ca408e19911585664952d',
    messagingSenderId: '541373305176',
    projectId: 'owl-ess-fc85e',
    storageBucket: 'owl-ess-fc85e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCCAs0CLYXTNNKWPRpEJTVrcEUxEfWNsw',
    appId: '1:541373305176:ios:d1891cf41e0457fc64952d',
    messagingSenderId: '541373305176',
    projectId: 'owl-ess-fc85e',
    storageBucket: 'owl-ess-fc85e.appspot.com',
    iosBundleId: 'com.owl.owl-ESS.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCCAs0CLYXTNNKWPRpEJTVrcEUxEfWNsw',
    appId: '1:541373305176:ios:d1891cf41e0457fc64952d',
    messagingSenderId: '541373305176',
    projectId: 'owl-ess-fc85e',
    storageBucket: 'owl-ess-fc85e.appspot.com',
    iosBundleId: 'com.owl.owl-ESS.RunnerTests',
  );
}
